version: "3.9"

services:
  app:
    build: .
    ports:
      - "${FLASK_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "server.py"]
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
